export const locationData = [
  { name: "Afghanistan", currency: "Afghani", symbol: "؋", code: "AFN" },
  { name: "Albania", currency: "Lek", symbol: "L", code: "ALL" },
  { name: "Algeria", currency: "Dinar", symbol: "د.ج", code: "DZD" },
  { name: "Andorra", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Angola", currency: "Kwanza", symbol: "Kz", code: "AOA" },
  { name: "Argentina", currency: "Peso", symbol: "$", code: "ARS" },
  { name: "Armenia", currency: "Dram", symbol: "֏", code: "AMD" },
  {
    name: "Australia",
    currency: "Australian Dollar",
    symbol: "$",
    code: "AUD",
  },
  { name: "Azerbaijan", currency: "Manat", symbol: "₼", code: "AZN" },
  { name: "Bahrain", currency: "Dinar", symbol: ".د.ب", code: "BHD" },
  { name: "Bangladesh", currency: "Taka", symbol: "৳", code: "BDT" },
  { name: "Belarus", currency: "Ruble", symbol: "Br", code: "BYN" },
  { name: "Belgium", currency: "Euro", symbol: "€", code: "EUR" },
  {
    name: "Benin",
    currency: "West African CFA Franc",
    symbol: "Fr",
    code: "XOF",
  },
  { name: "Bhutan", currency: "Ngultrum", symbol: "Nu.", code: "BTN" },
  { name: "Bolivia", currency: "Boliviano", symbol: "Bs.", code: "BOB" },
  {
    name: "Bosnia and Herzegovina",
    currency: "Convertible Mark",
    symbol: "KM",
    code: "BAM",
  },
  { name: "Botswana", currency: "Pula", symbol: "P", code: "BWP" },
  { name: "Brazil", currency: "Real", symbol: "R$", code: "BRL" },
  { name: "Brunei", currency: "Dollar", symbol: "$", code: "BND" },
  { name: "Bulgaria", currency: "Lev", symbol: "лв", code: "BGN" },
  {
    name: "Burkina Faso",
    currency: "West African CFA Franc",
    symbol: "Fr",
    code: "XOF",
  },
  { name: "Burundi", currency: "Franc", symbol: "Fr", code: "BIF" },
  { name: "Cambodia", currency: "Riel", symbol: "៛", code: "KHR" },
  {
    name: "Cameroon",
    currency: "Central African CFA Franc",
    symbol: "Fr",
    code: "XAF",
  },
  { name: "Canada", currency: "Canadian Dollar", symbol: "$", code: "CAD" },
  { name: "Chile", currency: "Peso", symbol: "$", code: "CLP" },
  { name: "China", currency: "Yuan Renminbi", symbol: "¥", code: "CNY" },
  { name: "Colombia", currency: "Peso", symbol: "$", code: "COP" },
  { name: "Comoros", currency: "Franc", symbol: "Fr", code: "KMF" },
  {
    name: "Congo",
    currency: "Central African CFA Franc",
    symbol: "Fr",
    code: "XAF",
  },
  { name: "Costa Rica", currency: "Colon", symbol: "₡", code: "CRC" },
  { name: "Croatia", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Cuba", currency: "Peso", symbol: "$", code: "CUP" },
  { name: "Cyprus", currency: "Euro", symbol: "€", code: "EUR" },
  {
    name: "Czech Republic",
    currency: "Czech Koruna",
    symbol: "Kč",
    code: "CZK",
  },
  { name: "Denmark", currency: "Krone", symbol: "kr", code: "DKK" },
  { name: "Djibouti", currency: "Franc", symbol: "Fr", code: "DJF" },
  { name: "Dominican Republic", currency: "Peso", symbol: "RD$", code: "DOP" },
  { name: "Egypt", currency: "Pound", symbol: "£", code: "EGP" },
  {
    name: "El Salvador",
    currency: "United States Dollar",
    symbol: "$",
    code: "USD",
  },
  { name: "Eritrea", currency: "Nakfa", symbol: "Nfk", code: "ERN" },
  { name: "Estonia", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Eswatini", currency: "Lilangeni", symbol: "L", code: "SZL" },
  { name: "Ethiopia", currency: "Birr", symbol: "Br", code: "ETB" },
  { name: "European Union", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Fiji", currency: "Fijian Dollar", symbol: "$", code: "FJD" },
  { name: "Finland", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "France", currency: "Euro", symbol: "€", code: "EUR" },
  {
    name: "Gabon",
    currency: "Central African CFA Franc",
    symbol: "Fr",
    code: "XAF",
  },
  { name: "Gambia", currency: "Dalasi", symbol: "D", code: "GMD" },
  { name: "Georgia", currency: "Lari", symbol: "₾", code: "GEL" },
  { name: "Germany", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Ghana", currency: "Cedi", symbol: "₵", code: "GHS" },
  { name: "Greece", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Guatemala", currency: "Quetzal", symbol: "Q", code: "GTQ" },
  { name: "Guinea", currency: "Guinean Franc", symbol: "Fr", code: "GNF" },
  {
    name: "Guinea-Bissau",
    currency: "West African CFA Franc",
    symbol: "Fr",
    code: "XOF",
  },
  { name: "Guyana", currency: "Guyana Dollar", symbol: "$", code: "GYD" },
  { name: "Honduras", currency: "Lempira", symbol: "L", code: "HNL" },
  { name: "Hong Kong", currency: "Dollar", symbol: "$", code: "HKD" },
  { name: "Hungary", currency: "Forint", symbol: "Ft", code: "HUF" },
  { name: "Iceland", currency: "Krona", symbol: "kr", code: "ISK" },
  { name: "India", currency: "Rupee", symbol: "₹", code: "INR" },
  { name: "Indonesia", currency: "Rupiah", symbol: "Rp", code: "IDR" },
  { name: "Iran", currency: "Rial", symbol: "﷼", code: "IRR" },
  { name: "Iraq", currency: "Dinar", symbol: "ع.د", code: "IQD" },
  { name: "Ireland", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Israel", currency: "Shekel", symbol: "₪", code: "ILS" },
  { name: "Italy", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Jamaica", currency: "Dollar", symbol: "$", code: "JMD" },
  { name: "Japan", currency: "Yen", symbol: "¥", code: "JPY" },
  { name: "Jordan", currency: "Dinar", symbol: "د.ا", code: "JOD" },
  { name: "Kazakhstan", currency: "Tenge", symbol: "₸", code: "KZT" },
  { name: "Kenya", currency: "Shilling", symbol: "Sh", code: "KES" },
  { name: "Kiribati", currency: "Australian Dollar", symbol: "$", code: "AUD" },
  { name: "Kosovo", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Kuwait", currency: "Dinar", symbol: "د.ك", code: "KWD" },
  { name: "Kyrgyzstan", currency: "Som", symbol: "с", code: "KGS" },
  { name: "Laos", currency: "Kip", symbol: "₭", code: "LAK" },
  { name: "Latvia", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Lebanon", currency: "Pound", symbol: "ل.ل", code: "LBP" },
  { name: "Lesotho", currency: "Loti", symbol: "L", code: "LSL" },
  { name: "Liberia", currency: "Dollar", symbol: "$", code: "LRD" },
  { name: "Libya", currency: "Dinar", symbol: "ل.د", code: "LYD" },
  { name: "Liechtenstein", currency: "Swiss Franc", symbol: "Fr", code: "CHF" },
  { name: "Lithuania", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Luxembourg", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Madagascar", currency: "Ariary", symbol: "Ar", code: "MGA" },
  { name: "Malawi", currency: "Kwacha", symbol: "MK", code: "MWK" },
  { name: "Malaysia", currency: "Ringgit", symbol: "RM", code: "MYR" },
  { name: "Maldives", currency: "Rufiyaa", symbol: "Rf", code: "MVR" },
  {
    name: "Mali",
    currency: "West African CFA Franc",
    symbol: "Fr",
    code: "XOF",
  },
  { name: "Malta", currency: "Euro", symbol: "€", code: "EUR" },
  {
    name: "Marshall Islands",
    currency: "United States Dollar",
    symbol: "$",
    code: "USD",
  },
  { name: "Mauritania", currency: "Ouguiya", symbol: "UM", code: "MRU" },
  { name: "Mauritius", currency: "Rupee", symbol: "₨", code: "MUR" },
  { name: "Mexico", currency: "Peso", symbol: "$", code: "MXN" },
  {
    name: "Micronesia",
    currency: "United States Dollar",
    symbol: "$",
    code: "USD",
  },
  { name: "Moldova", currency: "Leu", symbol: "L", code: "MDL" },
  { name: "Monaco", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Mongolia", currency: "Tugrik", symbol: "₮", code: "MNT" },
  { name: "Montenegro", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Morocco", currency: "Dirham", symbol: "د.م.", code: "MAD" },
  { name: "Mozambique", currency: "Metical", symbol: "MT", code: "MZN" },
  { name: "Myanmar", currency: "Kyat", symbol: "Ks", code: "MMK" },
  { name: "Namibia", currency: "Dollar", symbol: "$", code: "NAD" },
  { name: "Nauru", currency: "Australian Dollar", symbol: "$", code: "AUD" },
  { name: "Nepal", currency: "Rupee", symbol: "₨", code: "NPR" },
  { name: "Netherlands", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "New Zealand", currency: "Dollar", symbol: "$", code: "NZD" },
  { name: "Nicaragua", currency: "Cordoba", symbol: "C$", code: "NIO" },
  {
    name: "Niger",
    currency: "West African CFA Franc",
    symbol: "Fr",
    code: "XOF",
  },
  { name: "Nigeria", currency: "Naira", symbol: "₦", code: "NGN" },
  { name: "North Korea", currency: "Won", symbol: "₩", code: "KPW" },
  { name: "Norway", currency: "Krone", symbol: "kr", code: "NOK" },
  { name: "Oman", currency: "Rial", symbol: "ر.ع.", code: "OMR" },
  { name: "Pakistan", currency: "Rupee", symbol: "₨", code: "PKR" },
  { name: "Palau", currency: "United States Dollar", symbol: "$", code: "USD" },
  { name: "Panama", currency: "Balboa", symbol: "B/.", code: "PAB" },
  { name: "Papua New Guinea", currency: "Kina", symbol: "K", code: "PGK" },
  { name: "Paraguay", currency: "Guarani", symbol: "₲", code: "PYG" },
  { name: "Peru", currency: "Sol", symbol: "S/", code: "PEN" },
  { name: "Philippines", currency: "Peso", symbol: "₱", code: "PHP" },
  { name: "Poland", currency: "Zloty", symbol: "zł", code: "PLN" },
  { name: "Portugal", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Qatar", currency: "Riyal", symbol: "ر.ق", code: "QAR" },
  { name: "Romania", currency: "Leu", symbol: "lei", code: "RON" },
  { name: "Russia", currency: "Ruble", symbol: "₽", code: "RUB" },
  { name: "Rwanda", currency: "Franc", symbol: "Fr", code: "RWF" },
  {
    name: "Saint Kitts and Nevis",
    currency: "East Caribbean Dollar",
    symbol: "$",
    code: "XCD",
  },
  {
    name: "Saint Lucia",
    currency: "East Caribbean Dollar",
    symbol: "$",
    code: "XCD",
  },
  {
    name: "Saint Vincent and the Grenadines",
    currency: "East Caribbean Dollar",
    symbol: "$",
    code: "XCD",
  },
  { name: "Samoa", currency: "Tala", symbol: "WS$", code: "WST" },
  { name: "San Marino", currency: "Euro", symbol: "€", code: "EUR" },
  {
    name: "Sao Tome and Principe",
    currency: "Dobra",
    symbol: "Db",
    code: "STN",
  },
  { name: "Saudi Arabia", currency: "Riyal", symbol: "ر.س", code: "SAR" },
  {
    name: "Senegal",
    currency: "West African CFA Franc",
    symbol: "Fr",
    code: "XOF",
  },
  { name: "Serbia", currency: "Dinar", symbol: "дин", code: "RSD" },
  { name: "Seychelles", currency: "Rupee", symbol: "₨", code: "SCR" },
  { name: "Sierra Leone", currency: "Leone", symbol: "Le", code: "SLL" },
  { name: "Singapore", currency: "Dollar", symbol: "$", code: "SGD" },
  { name: "Slovakia", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Slovenia", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Solomon Islands", currency: "Dollar", symbol: "$", code: "SBD" },
  { name: "Somalia", currency: "Shilling", symbol: "Sh", code: "SOS" },
  { name: "South Africa", currency: "Rand", symbol: "R", code: "ZAR" },
  { name: "South Korea", currency: "Won", symbol: "₩", code: "KRW" },
  { name: "South Sudan", currency: "Pound", symbol: "£", code: "SSP" },
  { name: "Spain", currency: "Euro", symbol: "€", code: "EUR" },
  { name: "Sri Lanka", currency: "Rupee", symbol: "₨", code: "LKR" },
  { name: "Sudan", currency: "Pound", symbol: "£", code: "SDG" },
  { name: "Suriname", currency: "Dollar", symbol: "$", code: "SRD" },
  { name: "Sweden", currency: "Krona", symbol: "kr", code: "SEK" },
  { name: "Switzerland", currency: "Franc", symbol: "Fr", code: "CHF" },
  { name: "Syria", currency: "Pound", symbol: "£", code: "SYP" },
  { name: "Taiwan", currency: "New Taiwan Dollar", symbol: "NT$", code: "TWD" },
  { name: "Tajikistan", currency: "Somoni", symbol: "ЅМ", code: "TJS" },
  { name: "Tanzania", currency: "Shilling", symbol: "Sh", code: "TZS" },
  { name: "Thailand", currency: "Baht", symbol: "฿", code: "THB" },
  {
    name: "Timor-Leste",
    currency: "United States Dollar",
    symbol: "$",
    code: "USD",
  },
  {
    name: "Togo",
    currency: "West African CFA Franc",
    symbol: "Fr",
    code: "XOF",
  },
  { name: "Tonga", currency: "Paʻanga", symbol: "T$", code: "TOP" },
  { name: "Trinidad and Tobago", currency: "Dollar", symbol: "$", code: "TTD" },
  { name: "Tunisia", currency: "Dinar", symbol: "د.ت", code: "TND" },
  { name: "Turkey", currency: "Lira", symbol: "₺", code: "TRY" },
  { name: "Turkmenistan", currency: "Manat", symbol: "m", code: "TMT" },
  { name: "Tuvalu", currency: "Australian Dollar", symbol: "$", code: "AUD" },
  { name: "Uganda", currency: "Shilling", symbol: "Sh", code: "UGX" },
  { name: "Ukraine", currency: "Hryvnia", symbol: "₴", code: "UAH" },
  {
    name: "United Arab Emirates",
    currency: "Dirham",
    symbol: "د.إ",
    code: "AED",
  },
  {
    name: "United Kingdom",
    currency: "Pound Sterling",
    symbol: "£",
    code: "GBP",
  },
  { name: "United States", currency: "Dollar", symbol: "$", code: "USD" },
  { name: "Uruguay", currency: "Peso", symbol: "$", code: "UYU" },
  { name: "Uzbekistan", currency: "Som", symbol: "сўм", code: "UZS" },
  { name: "Vanuatu", currency: "Vatu", symbol: "VT", code: "VUV" },
  { name: "Vatican City", currency: "Euro", symbol: "€", code: "EUR" },
  {
    name: "Venezuela",
    currency: "Bolívar Soberano",
    symbol: "Bs.",
    code: "VES",
  },
  { name: "Vietnam", currency: "Dong", symbol: "₫", code: "VND" },
  { name: "Yemen", currency: "Rial", symbol: "﷼", code: "YER" },
  { name: "Zambia", currency: "Kwacha", symbol: "ZK", code: "ZMW" },
  { name: "Zimbabwe", currency: "Zimbabwean Dollar", symbol: "$", code: "ZWL" },
];
