import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import Breadcrumb from "@/components/Breadcrumb";
import NetworkStatus from "@/components/NetworkStatus";
import { ToastProvider } from "@/contexts/ToastContext";
import { Toast } from "@/components/Toast";

// InriaSans fonts
const inriaBold = localFont({
  src: "./fonts/inria/InriaSans-Bold.ttf",
  variable: "--font-inria-bold",
  weight: "100 900",
});

const inriaLight = localFont({
  src: "./fonts/inria/InriaSans-Light.ttf",
  variable: "--font-inria-light",
  weight: "100 900",
});

const inriaRegular = localFont({
  src: "./fonts/inria/InriaSans-Regular.ttf",
  variable: "--font-inria-regular",
  weight: "100 900",
});

// Inter fonts
const interBold = localFont({
  src: "./fonts/inter/Inter-Bold.ttf",
  variable: "--font-inter-bold",
  weight: "100 900",
});

const interLight = localFont({
  src: "./fonts/inter/Inter-Light.ttf",
  variable: "--font-inter-light",
  weight: "100 900",
});

const interRegular = localFont({
  src: "./fonts/inter/Inter-Regular.ttf",
  variable: "--font-inter-regular",
  weight: "100 900",
});

const interMedium = localFont({
  src: "./fonts/inter/Inter-Medium.ttf",
  variable: "--font-inter-medium",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Oak Scientifics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inriaBold.variable} ${inriaRegular.variable} ${inriaLight.variable} ${interLight.variable} ${interRegular.variable} ${interBold.variable} ${interMedium.variable} antialiased`}
      >
        <ToastProvider>
          <Nav />
          <div className={`font-[family-name:var(--font-inter-regular)] pt-28`}>
            {children}
          </div>
          <Footer />
          <NetworkStatus />
          <Toast />
          <div id="portal-root" />
        </ToastProvider>
      </body>
    </html>
  );
}
